title: Bryan Scott
email: bryan@bryanscott.ink
description: >- # this means to ignore newlines until "author:"
  Put a great description here.
author: "Bryan Scott" #  Default is your site title.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bryanscott.ink" # the base hostname & protocol for your site, e.g. http://example.com
# # Your social accounts.
social:
#   github: github_username
  twitter: bryanscottherr
  facebook: bryanscottherr
#   instagram: instagram_username
  linkedin: bryanherr
#   weibo: weibo_username

# Build settings
theme: jekyll-theme-persephone
plugins:
  - jekyll-feed
  - jekyll-books

# Theme Settings

# Your site's logo. Will be shown on the left top of your page.
logo: /img/favicon-32x32.png
# If the images of our blog are stored in an external cloud. You can use the jekyll-img-prefix plugin and set your images' base URL here.
# img_prefix: https://your-img-cdn.com
# The RSS link of your blog.
rss: "/feed.xml"

# The followings are settings for displays of your blog.
theme_setting:
  # The slides count in the slides layout. Default is 4.
  slides_count: 5
  # The ← back URL on the top of your post page. Default is your site's home page.
  blog_page: "blog.md"
  # The URL on your name on the bottom of your post and page. Default is your site's home page.
  about_page: "about.md"
  #  The URL of the menu icon(which has three black lines). Will be shown on the slides/book/chapter layouts It won't be shown if blank.
  archive_page: "books.md"
  # The nav links on the top right of home/page/post/blog layout. You can set a local page(by setting a layout's path) or and external link ( both title and url are required) here.
  nav_pages:
    - "books.md"
    - "blog.md"
    - "about.md"
#  # Every default value in the following settings is false. You can set them globally here or separately in a single post/page/chapter.
#   code: true # Code highlight.
#   math: true # Mathjax
#   mermaid: true # Mermaid

# head_code: |
#   <!-- Extra codes in the head of your site pages. You can add your Google Analysis codes here! -->

# # The settings of comments.
# comment:
#   # You should set it to enable comment
#   enabled: true
#   # Your comment provider
#   provider: disqus # static/disqus
#   # If provider == disqus
#   disqus:
#     name: website_name
#   # Or provider == static
#   static:
#     # Your static comment url.
#     postUrl:  https://api.staticman.net/v2/connect/GITHUB-USERNAME/GITHUB-REPOSITORY
# # The settings of local smileys used in static comments. The jekyll-smiley plugin is required.
# smiley:
#   enabled: true
#   dir: img/smileys
